set_valve_timer:
  name: Set valve timer
  description: Set the valve to run for a specific duration.
  target:
    entity:
      integration: ecowitt_iot
      domain: switch
  fields:
    duration:
      name: Duration
      description: Duration to run the valve
      required: true
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes

set_power_timer:
  name: Set power timer
  description: Set the power outlet to run for a specific duration.
  target:
    entity:
      integration: ecowitt_iot
      domain: switch
  fields:
    duration:
      name: Duration
      description: Duration to keep the power on
      required: true
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
